"""Plain-text report renderer — terminal-friendly summary from ``AuditRun``.

What: ``render_txt()`` and ``write_txt_report()`` produce ``report.txt``.
Where: Called from ``render/reports.write_run_reports()`` when ``txt`` is in output formats.
How: Uses the same grouped findings as HTML reports; no external dependencies.
"""

from __future__ import annotations

from pathlib import Path

from webaudit.models.run import AuditRun
from webaudit.render.context import build_report_context


def render_txt(run: AuditRun, *, variant: str = "technical", theme: str = "dark") -> str:
    ctx = build_report_context(run, variant=variant, theme=theme)
    lines: list[str] = [
        "Web Audit Report",
        "=" * 72,
        f"Target:     {ctx['target_url']}",
        f"Framework:  {ctx['framework']} ({ctx['framework_confidence']})",
        f"Scanned:    {ctx['scanned_at']}",
        f"Variant:    {variant}",
        "",
        "Scores",
        "-" * 72,
        f"  Hygiene:   {run.scores.hygiene}",
        f"  Exposure:  {run.scores.exposure}",
        f"  Verdict:   {run.scores.verdict}",
        "",
    ]

    def _section(title: str, findings: list) -> None:
        lines.append(title)
        lines.append("-" * 72)
        if not findings:
            lines.append("  (none)")
            lines.append("")
            return
        for finding in findings:
            lines.append(
                f"  [{finding.severity.value}] {finding.category} / {finding.item} — "
                f"{finding.status}"
            )
            if finding.detail:
                lines.append(f"      {finding.detail}")
        lines.append("")

    _section("Action findings", ctx["action_findings"])
    _section("Verify", ctx["verify_findings"])
    _section("Expected / informational", ctx["expected_findings"] + ctx["info_findings"])

    if ctx["dns_cards"]:
        lines.append("DNS summary")
        lines.append("-" * 72)
        for card in ctx["dns_cards"]:
            lines.append(f"  {card['label']}: {card['value']}")
            if card.get("summary"):
                lines.append(f"      {card['summary']}")
        lines.append("")

    lines.extend(
        [
            "=" * 72,
            f"Generated by Web Audit v{run.meta.webaudit_version} · {len(run.findings)} checks",
        ]
    )
    return "\n".join(lines) + "\n"


def write_txt_report(
    run: AuditRun,
    run_dir: Path,
    *,
    variant: str = "technical",
    theme: str = "dark",
    txt_name: str = "report.txt",
) -> Path:
    txt_path = run_dir / txt_name
    txt_path.write_text(render_txt(run, variant=variant, theme=theme), encoding="utf-8")
    return txt_path
